"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

ALLOWED_HOSTS = [
    h.strip() for h in config("ALLOWED_HOSTS", default="").split(",") if h.strip()
]
if DEBUG:
    ALLOWED_HOSTS.extend(["localhost", "127.0.0.1", "testserver"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "django_rest_passwordreset",
    "django_extensions",
    "corsheaders",
    "apps.accounts",
    "apps.agents",
    "apps.customers",
    "apps.items",
    "apps.orders",
    "apps.dashboard",
    "apps.admins",
    "apps.business",
    "apps.notification",
    "transports",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# SMTP Server
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@example.com")

# VAPID
PUBLIC_VAPID_KEY = config("PUBLIC_VAPID_KEY", "")
PRIVATE_VAPID_KEY = config("PRIVATE_VAPID_KEY", "")


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT", cast=int),
    }
}

# CELERY
# Note: an empty CELERY_BROKER_URL in .env would otherwise win over the
# default and make Celery/kombu silently fall back to amqp://localhost.
CELERY_BROKER_URL = (
    config("CELERY_BROKER_URL", "redis://localhost:6379/0")
    or "redis://localhost:6379/0"
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# FCM (Firebase Cloud Messaging) for mobile push.
# Path to the Firebase Admin service-account JSON. When empty/None, FCM
# dispatch is skipped (best-effort) without affecting existing web push.
FIREBASE_CREDENTIALS = config("FIREBASE_CREDENTIALS", default="") or None

CELERY_BEAT_SCHEDULE = {
    "cleanup-orphaned-media-daily": {
        "task": "apps.items.tasks.cleanup_orphaned_media_task",
        "schedule": crontab(hour=0, minute=0),
    },
    "purge-archived-items-daily": {
        "task": "apps.items.tasks.purge_archived_items_task",
        "schedule": crontab(hour=1, minute=0),
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Stock Management System API",
    "DESCRIPTION": "Backend APIs for Admin & Agent stock/order management",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SECURITY": [{"BearerAuth": []}],
    "SECURITY_DEFINITIONS": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT Authorization header. Example: Bearer <token>",
        }
    },
}

_default_cors = "http://localhost:3000,https://stockflow-sigma.vercel.app"
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in config("CORS_ALLOWED_ORIGINS", default=_default_cors).split(",")
    if o.strip()
]


CORS_ALLOW_ALL_ORIGINS = config("CORS_ALLOW_ALL_ORIGINS", default=False, cast=bool)
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "content-type",
    "x-csrftoken",
    "authorization",
    "ngrok-skip-browser-warning",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

CSRF_TRUSTED_ORIGINS = [o for o in CORS_ALLOWED_ORIGINS if o.startswith("https://")]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
# Production security
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

GST_RATE = config("GST_RATE", default=5, cast=float)

# Admin-created draft orders expire after this many hours.
ADMIN_DRAFT_EXPIRY_HOURS = config("ADMIN_DRAFT_EXPIRY_HOURS", default=24, cast=int)

# Items are considered "archived" once they have been out of stock for this
# many days (matches the /api/items/archived/ cutoff).
ARCHIVE_AFTER_DAYS = config("ARCHIVE_AFTER_DAYS", default=30, cast=int)

# Archived items are permanently (soft) deleted once they have been archived
# for this many more days. Total: ARCHIVE_AFTER_DAYS + ARCHIVED_ITEM_RETENTION_DAYS.
ARCHIVED_ITEM_RETENTION_DAYS = config(
    "ARCHIVED_ITEM_RETENTION_DAYS", default=30, cast=int
)

# Master switch for the scheduled archived-item purge.
ARCHIVED_ITEM_PURGE_ENABLED = config(
    "ARCHIVED_ITEM_PURGE_ENABLED", default=True, cast=bool
)

# How many archived items to process per purge run.
ARCHIVED_ITEM_PURGE_BATCH = config("ARCHIVED_ITEM_PURGE_BATCH", default=500, cast=int)

# Incremental item sync for the mobile Inventory screen.
ITEM_SYNC_MAX_AGE_DAYS = config("ITEM_SYNC_MAX_AGE_DAYS", default=14, cast=int)
ITEM_SYNC_MAX_DELTA_ITEMS = config("ITEM_SYNC_MAX_DELTA_ITEMS", default=500, cast=int)

TIME_ZONE = "Asia/Kolkata"
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}
