# Generated by Django 5.2.9 on 2026-03-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('items', '0002_alter_itemvariant_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_items', to='agents.agent')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_agents', to='items.item')),
            ],
            options={
                'unique_together': {('agent', 'item')},
            },
        ),
    ]
