# Generated by Django 5.2.14 on 2026-09-26 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('customers', '0001_initial'),
        ('items', '0001_initial'),
        ('transports', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('EDITING', 'Editing'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched')], default='DRAFT', max_length=20)),
                ('computed_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('final_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('price_override_reason', models.CharField(blank=True, default='', max_length=200)),
                ('price_overridden_at', models.DateTimeField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('lr_number', models.CharField(blank=True, default='', max_length=50)),
                ('shortfall_reason', models.CharField(blank=True, default='', max_length=200)),
                ('edit_snapshot', models.JSONField(blank=True, default=list)),
                ('editing_started_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agents.agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('preferred_transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='transports.transport')),
                ('price_overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priced_orders', to=settings.AUTH_USER_MODEL)),
                ('transport_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_orders', to='transports.transport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_name', models.CharField(default='Unknown Fabric', max_length=100)),
                ('rate_per_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('variant_image', models.URLField(blank=True, null=True)),
                ('variant_display_order', models.CharField(blank=True, default='', max_length=100)),
                ('ordered_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('allocated_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.fabric')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.fabricvariant')),
            ],
        ),
        migrations.CreateModel(
            name='PackingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_size', models.DecimalField(decimal_places=3, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('plan_override', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_rounds', to='items.fabricvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metres', models.DecimalField(decimal_places=3, max_digits=14)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('is_priority_award', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orders.orderitem')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='orders.packinground')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.PositiveIntegerField(db_index=True)),
                ('action', models.CharField(choices=[('ITEM_DELETED', 'Item Deleted'), ('ORDER_DELETED', 'Order Deleted'), ('ORDER_EDITED', 'Order Edited'), ('DISPATCHED', 'Dispatched'), ('EDIT_STARTED', 'Edit Started'), ('EDIT_SAVED', 'Edit Saved'), ('EDIT_CANCELLED', 'Edit Cancelled'), ('PRICE_OVERRIDE', 'Price Overridden'), ('PRICE_OVERRIDE_CLEARED', 'Price Override Cleared'), ('ALLOCATION_MADE', 'Stock Allocated'), ('ALLOCATION_REVERSED', 'Allocation Reversed'), ('ROUND_CANCELLED', 'Packing Round Cancelled')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='orders.order')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_ref', '-created_at'], name='orders_orde_order_r_647f2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserViewedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'order')},
            },
        ),
    ]
