# Generated by Django 5.2.14 on 2026-10-02 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_rate_per_meter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rate_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rate_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repriced_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='action',
            field=models.CharField(choices=[('ITEM_DELETED', 'Item Deleted'), ('ORDER_DELETED', 'Order Deleted'), ('ORDER_EDITED', 'Order Edited'), ('DISPATCHED', 'Dispatched'), ('EDIT_STARTED', 'Edit Started'), ('EDIT_SAVED', 'Edit Saved'), ('EDIT_CANCELLED', 'Edit Cancelled'), ('PRICE_OVERRIDE', 'Price Overridden'), ('PRICE_OVERRIDE_CLEARED', 'Price Override Cleared'), ('ITEM_RATE_OVERRIDE', 'Item Rate Overridden'), ('ITEM_RATE_OVERRIDE_CLEARED', 'Item Rate Override Cleared'), ('ALLOCATION_MADE', 'Stock Allocated'), ('ALLOCATION_REVERSED', 'Allocation Reversed'), ('ROUND_CANCELLED', 'Packing Round Cancelled')], max_length=30),
        ),
    ]
