# Generated by Django 5.2.14 on 2026-10-02 12:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_fabricroll'),
        ('orders', '0002_orderitem_original_rate_per_meter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metres', models.DecimalField(decimal_places=3, max_digits=14)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('is_reversed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_allocations', to='orders.allocation')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roll_allocations', to='items.fabricroll')),
            ],
            options={
                'ordering': ['allocation_id', 'sequence', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('metres__gt', Decimal('0'))), name='rollallocation_metres_positive')],
            },
        ),
    ]
