# Generated by Django 5.2.13 on 2026-04-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_item_name_orderitem_item_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(default='gents', max_length=10),
        ),
    ]
