# Generated by Django 5.2.9 on 2026-04-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched')], default='DRAFT', max_length=20),
        ),
    ]
