# Generated by Django 5.2.14 on 2026-10-04 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_packingbundle_rollallocation_bundle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='orders.packingbundle'),
        ),
        migrations.AddField(
            model_name='packingbundle',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('EDITING', 'Editing'), ('PACKED', 'Packed'), ('PARTIALLY_DISPATCHED', 'Partially Dispatched'), ('DISPATCHED', 'Dispatched')], default='DRAFT', max_length=20),
        ),
    ]
