# Generated by Django 5.2.13 on 2026-04-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='editing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reservation_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('EDITING', 'Editing'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='action',
            field=models.CharField(choices=[('ITEM_DELETED', 'Item Deleted'), ('ORDER_DELETED', 'Order Deleted'), ('ORDER_EDITED', 'Order Edited'), ('DISPATCHED', 'Dispatched'), ('EDIT_STARTED', 'Edit Started'), ('EDIT_SAVED', 'Edit Saved'), ('EDIT_CANCELLED', 'Edit Cancelled')], max_length=20),
        ),
    ]
