# Generated by Django 5.2.13 on 2026-05-08 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentitem'),
        ('orders', '0007_add_user_viewed_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
    ]
