// @vitest-environment node
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import QRCode from 'qrcode'
import { readBarcodes } from '../../node_modules/.pnpm/zxing-wasm@3.1.0_@types+emscripten@1.41.5/node_modules/zxing-wasm/dist/es/full/index.js'

/**
 * Cross-platform QR parity — DOCUMENTED DIVERGENCE (kept as-is).
 *
 * Fixed UUID rendered by the JS `qrcode` encoder for both error-correction
 * levels used by the two label kinds: EC L → version 2 (25×25), EC M →
 * version 3 (29×29). The Dart `qr` encoder (qr_flutter 4.1.0) renders 29×29
 * for BOTH levels, so the module matrices are NOT byte-identical across
 * platforms — but both encode the exact same payload and are scannable.
 * See mobile/test/qr_label_test.dart for the Dart side of this check.
 *
 * Decode-equality is verified here offline with the ZXing WASM decoder that
 * ships inside the repo's dependency tree (`zxing-wasm`, pulled in by the app's
 * own `@yudiel/react-qr-scanner` → `barcode-detector`). The web-encoded QR and
 * the Dart-encoded QR fixtures (`tests/fixtures/dart-qr-*.png`, generated by
 * the Dart `qr` encoder) both decode back to the same UUID string. A final
 * manual scan of a printed label is still recommended as a real-world check.
 */
const SAMPLE_UUID = '123e4567-e89b-12d3-a456-426614174000';

describe('qr-code parity (web encoder)', () => {
  it('error correction L uses version 2 (25×25)', () => {
    const code = QRCode.create(SAMPLE_UUID, { errorCorrectionLevel: 'L' });
    expect(code.modules.size).toBe(25);
  });

  it('error correction M uses version 3 (29×29)', () => {
    const code = QRCode.create(SAMPLE_UUID, { errorCorrectionLevel: 'M' });
    expect(code.modules.size).toBe(29);
  });
});

describe('qr decode-equality (offline ZXing WASM)', () => {
  async function decodeText(pngBytes: Uint8Array): Promise<string> {
    const results = await readBarcodes(pngBytes);
    const text = results.map((r) => r.text).find((t) => t != null);
    expect(text).toBeDefined();
    return text!;
  }

  it('web qrcode EC L (25×25, single label) decodes to the UUID', async () => {
    const png = (await QRCode.toBuffer(SAMPLE_UUID, {
      errorCorrectionLevel: 'L',
    })) as Uint8Array;
    expect(await decodeText(png)).toBe(SAMPLE_UUID);
  });

  it('web qrcode EC M (29×29, print-all label) decodes to the UUID', async () => {
    const png = (await QRCode.toBuffer(SAMPLE_UUID, {
      errorCorrectionLevel: 'M',
    })) as Uint8Array;
    expect(await decodeText(png)).toBe(SAMPLE_UUID);
  });

  it('Dart qr EC L fixture (29×29, mobile single label) decodes to the UUID', async () => {
    const png = readFileSync(
      fileURLToPath(new URL('../fixtures/dart-qr-L.png', import.meta.url)),
    );
    expect(await decodeText(new Uint8Array(png))).toBe(SAMPLE_UUID);
  });

  it('Dart qr EC M fixture (29×29, mobile print-all label) decodes to the UUID', async () => {
    const png = readFileSync(
      fileURLToPath(new URL('../fixtures/dart-qr-M.png', import.meta.url)),
    );
    expect(await decodeText(new Uint8Array(png))).toBe(SAMPLE_UUID);
  });
});