# Generated by Django 5.2.13 on 2026-04-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business',
            field=models.CharField(blank=True, choices=[('gents', 'Gents'), ('kids', 'Kids')], max_length=10),
        ),
    ]
