# Generated by Django 5.2.9 on 2026-05-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
