# Generated by Django 5.2.14 on 2026-09-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('transports', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True)),
                ('contact', models.CharField(max_length=20)),
                ('gst', models.CharField(blank=True, default='', max_length=20)),
                ('priority_override', models.IntegerField(blank=True, help_text='Lower wins when ranking packing priority. Blank = rank by sales.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='agents.agent')),
                ('preferred_transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='transports.transport')),
            ],
        ),
    ]
