# Generated by Django 5.2.9 on 2026-05-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gst',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
