# Generated by Django 4.2.24 on 2026-05-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
        ('customers', '0003_alter_customer_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='transports.transport'),
        ),
    ]
