# Generated by Django 5.2.14 on 2026-05-17 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_deactivated_at_agent_is_active'),
        ('customers', '0006_customer_deactivated_at_customer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='agents.agent'),
        ),
    ]
