# Generated by Django 4.2.24 on 2026-05-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_brand_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
