# Generated by Django 5.2.14 on 2026-09-26 14:03

import apps.items.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('out_of_stock_since', models.DateTimeField(blank=True, null=True)),
                ('catalog_updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FabricVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.items.models.fabric_variant_image_path)),
                ('stock_meters', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('stock_updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='items.fabric')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
