# Generated by Django 5.2.9 on 2026-03-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariant',
            name='size',
            field=models.CharField(choices=[('20-24', '20-24'), ('26-30', '26-30'), ('32-36', '32-36'), ('38', '38'), ('S', 'S'), ('M,L,XL', 'M,L,XL'), ('XXL', 'XXL')], max_length=10),
        ),
    ]
