# Generated by Django 5.2.14 on 2026-09-26 14:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricvariant',
            name='stock_meters',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
