# Generated by Django 5.2.14 on 2026-10-02 12:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_fabricvariant_stock_meters'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=32, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=100)),
                ('original_meters', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('remaining_meters', models.DecimalField(decimal_places=3, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='items.fabricvariant')),
            ],
            options={
                'ordering': ['roll_number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('original_meters__gt', Decimal('0'))), name='fabricroll_original_meters_positive'), models.CheckConstraint(condition=models.Q(('remaining_meters__gte', Decimal('0'))), name='fabricroll_remaining_not_negative'), models.CheckConstraint(condition=models.Q(('remaining_meters__lte', models.F('original_meters'))), name='fabricroll_remaining_within_original')],
            },
        ),
    ]
