# Generated by Django 5.2.14 on 2026-10-04 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_fabricroll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metres', models.DecimalField(decimal_places=3, max_digits=14)),
                ('stock_before', models.DecimalField(decimal_places=3, max_digits=14)),
                ('stock_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(choices=[('opening_figure_discarded', 'Opening figure replaced by first roll')], max_length=40)),
                ('roll_number', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='items.fabricvariant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
