# Generated by Django 5.2.9 on 2026-04-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_variant_refactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariant',
            name='color_order',
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='stock',
        ),
        migrations.AlterField(
            model_name='itemvariantsize',
            name='size',
            field=models.CharField(choices=[('20-24', '20-24'), ('26-30', '26-30'), ('32-36', '32-36'), ('38', '38'), ('S', 'S'), ('M,L,XL', 'M,L,XL'), ('XXL', 'XXL')], max_length=10),
        ),
    ]
