# Generated by Django 4.2.24 on 2026-05-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='out_of_stock_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
