# Generated by Django 5.2.14 on 2026-05-17 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_brand_deactivated_at_brand_is_active'),
        ('items', '0007_item_out_of_stock_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='business.brand'),
        ),
    ]
