# Generated by Django 5.2.15 on 2026-08-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_item_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='display_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
