# Generated by Django 5.2.14 on 2026-09-20 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_itemvariant_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='catalog_updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itemvariantsize',
            name='stock_updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
